<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="FileStorage\" />
    <Folder Include="Email\" />
    <Folder Include="Logging\" />
    <Folder Include="Authentication\" />
    <Folder Include="Cache\" />
    <Folder Include="Import\" />
    <Folder Include="Export\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PEMS.Domain\PEMS.Domain.csproj" />
    <ProjectReference Include="..\PEMS.Shared\PEMS.Shared.csproj" />
  </ItemGroup>

</Project>
