<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Chat\" />
    <Folder Include="Import\" />
    <Folder Include="Embeddings\" />
    <Folder Include="Knowledge\" />
    <Folder Include="Parser\" />
    <Folder Include="Prompt\" />
    <Folder Include="OCR\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PEMS.Application\PEMS.Application.csproj" />
    <ProjectReference Include="..\PEMS.Domain\PEMS.Domain.csproj" />
    <ProjectReference Include="..\PEMS.Shared\PEMS.Shared.csproj" />
  </ItemGroup>

</Project>
